default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")
    build_app(
      scheme: "TvMazeApp",
      cloned_source_packages_path: ".build/SourcePackages",
      derived_data_path: ".build/DerivedData",
      build_path: ".build",
      output_directory: ".build",
      buildlog_path: ".build/build_log"
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Run tests"
  lane :test do
    scan(
      scheme: "TvMazeApp",
      device: "iPhone 12 Pro",
      cloned_source_packages_path: ".build/SourcePackages",
      derived_data_path: ".build/DerivedData"
    )
  end

  desc "Upload dSYMs to Sentry"
  lane :upload_symbols do
    download_dsyms
    sentry_upload_dsym(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: 'grdsdev',
      project_slug: 'fintop'
    )
  end
end
